on: push

jobs:
  test:
    name: testDebugUnitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew testDebugUnitTest
  assembleDebug:
    name: assembleDebug
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v1
        with:
          name: TinoDebugApk
          path: app/build/outputs/apk/debug/app-debug.apk
  bundleRelease:
    name: bundleRelease
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json
      - run: |
          echo '${{ secrets.RELEASE_KEYSTORE_FILE }}' > release.keystore.asc
          gpg -d --passphrase '${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}' --batch release.keystore.asc > app/release.keystore
      - run: |
          ./gradlew bundleRelease -PTino.Keystore.Password='${{ secrets.RELEASE_KEYSTORE_PASSWORD }}' -PTino.Keystore.KeyAlias='${{ secrets.RELEASE_KEYSTORE_KEY_ALIAS }}' -PTino.KeyStore.KeyPassword='${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}'
      - uses: actions/upload-artifact@v1
        with:
          name: TinoReleaseAab
          path: app/build/outputs/bundle/release/
      - uses: actions/upload-artifact@v1
        with:
          name: TinoReleaseMappingFile
          path: app/build/outputs/mapping/release/mapping.txt